### ISSUE TITLE
package.scm 内の要求バージョンの指定について

### ISSUE THREAD

**Issue by Hamayama** [SaitoAtsushi/Gauche-zip-archive#1]
以下のようにバージョンに _ を付けて指定すると、プレリリース版も含められるようです。
  :require (("Gauche" (>= "0.9.5_")))
(「過去のすべてのプレリリース版で動作する」というわけではないでしょうが。。。)

**Comment by SaitoAtsushi** [comment]
バージョン比較は [gauche.version](http://practical-scheme.net/gauche/man/?l=jp&p=gauche.version) モジュールが使われています。  この仕様通りであれば  `"0.9.5_"` は適切とは言えないですね。 `_` の後に一文字以上必要です。  現在の HEAD に付けられているバージョンナンバーは `"0.9.5_pre1"` となっているのでこれを使うのが妥当でしょう。

ご指摘のように pre1 の途中でも変更が入っていて確実ではないので、かといってその次にしようと `:require (("Gauche" (> "0.9.5_pre1")))` にしてしまっては現行 HEAD では使えず……という感じで迷って、仮の指定として確実なところを書いた次第です。

shiro さんは[演算子を付け加えるという考え](https://twitter.com/anohana/status/738916439906603009)を示しているので、このあたりが一段落つくまで先送りしようと思っていたのですが、考えてみると pre1 を使っている人なら最新を追っている人でしょうから中途半端なところを気にする必要もないですね。 pre1 以上なら OK ということで修正してしまいます。

**Comment by Hamayama** [comment]
HEAD のリファレンスマニュアル (doc/modgauche.texi) をみると、
gauche.version の項目に、プレリリース版の _ のみによる指定についての記述が追加されています。
ソース上は、空文字列はバージョンが -1 の扱いになるようです。
(lib/gauche/version.scm の relnum-decompose 手続きより)
ただ、BNF の方は変更がないので、たしかに食い違っているようです。
演算子の追加の話とも一致しないので、あとで WiLiKi で確認してみます。。。

**Comment by Hamayama** [comment]
ユーザの視点からすると、
  :require (("Gauche" (>= "0.9.5_")))
より
  :require (("Gauche" (>= "0.9.5_pre1")))
の方が確かによさそうです。
